# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcli < Formula
  desc "Lightweight Docker Compose and Git management CLI"
  homepage "https://github.com/oleg-koval/dcli"
  version "0.1.0-27-g0a0e277"
  license "MIT"

  depends_on "docker" => :optional
  depends_on "git" => :optional

  on_macos do
    on_intel do
      url "https://github.com/oleg-koval/dcli/releases/download/v0.1.0-27-g0a0e277/dcli-0.1.0-27-g0a0e277-darwin-amd64.tar.gz"
      sha256 "032077d22967f34d3bd3e434e3390ef9315bfe98e2806b05669191281bc7ca79"

      def install
        bin.install "dcli"
      end
    end
    on_arm do
      url "https://github.com/oleg-koval/dcli/releases/download/v0.1.0-27-g0a0e277/dcli-0.1.0-27-g0a0e277-darwin-arm64.tar.gz"
      sha256 "9ef8540cf96796be17814eeddad7788360a8a707ce891398c4a10d03b1f0c6ea"

      def install
        bin.install "dcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oleg-koval/dcli/releases/download/v0.1.0-27-g0a0e277/dcli-0.1.0-27-g0a0e277-linux-amd64.tar.gz"
        sha256 "ed0ae46f848ec9c01a2effafb4c9a2e28252195625b7f6d54dfd1dbfd2de00c9"

        def install
          bin.install "dcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oleg-koval/dcli/releases/download/v0.1.0-27-g0a0e277/dcli-0.1.0-27-g0a0e277-linux-arm64.tar.gz"
        sha256 "f7aea644e48aea0ba74409f9a0c0e2656c0357b07131224430eae277bd92347d"

        def install
          bin.install "dcli"
        end
      end
    end
  end

  test do
    system "#{bin}/dcli --version"
  end
end
