# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcli < Formula
  desc "Lightweight Docker Compose and Git management CLI"
  homepage "https://github.com/oleg-koval/dcli"
  version "0.2.0"
  license "MIT"

  depends_on "docker" => :optional
  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oleg-koval/dcli/releases/download/v0.2.0/dcli-0.2.0-darwin-amd64.tar.gz"
      sha256 "668482d41393eee1cd2c5274de9ed36b84d3af603b4aa6bded2d2a2c872fd769"

      define_method(:install) do
        bin.install "dcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oleg-koval/dcli/releases/download/v0.2.0/dcli-0.2.0-darwin-arm64.tar.gz"
      sha256 "3a26e6d263093c1779924a5e375922da30f1c21d4d800897b7c088ffa0a6f0d6"

      define_method(:install) do
        bin.install "dcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oleg-koval/dcli/releases/download/v0.2.0/dcli-0.2.0-linux-amd64.tar.gz"
      sha256 "89fda4eec5974838bab60f6580e5017d99177fc413df921fd5648b6f5d319d91"
      define_method(:install) do
        bin.install "dcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oleg-koval/dcli/releases/download/v0.2.0/dcli-0.2.0-linux-arm64.tar.gz"
      sha256 "ed52fb92b89f97c87565892188fb2f9e39078862326afa7b31a9092afcc2f1dc"
      define_method(:install) do
        bin.install "dcli"
      end
    end
  end

  test do
    system "#{bin}/dcli --version"
  end
end
